data01<-read.table("household_power_consumption.txt", header = TRUE, sep = ";",stringsAsFactors = FALSE)
data01$date_time<-paste(data01$Date,data01$Time)
data01$date_time<-strptime(data01$date_time,"%d/%m/%Y %H:%M:%S")
data01$date_time<-as.POSIXct(data01$date_time)
data02<-filter(data01,date_time>="2007-02-01" & date_time<"2007-02-03")
##data01$Date<-as.Date(data01$Date,"%d/%m/%Y")
data02$Global_active_power<-as.numeric(data02$Global_active_power)
data02$Sub_metering_1<-as.numeric(data02$Sub_metering_1)
data02$Sub_metering_2<-as.numeric(data02$Sub_metering_2)
data02$Sub_metering_3<-as.numeric(data02$Sub_metering_3)
data02$Global_reactive_power<-as.numeric(data02$Global_reactive_power)
data02$Voltage<-as.numeric(data02$Voltage)

hist(data02$Global_active_power,col = "red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.copy(png,file="plot01.png")
dev.off()

plot(data02$date_time,data02$Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)",xlab="")
dev.copy(png,file="plot2.png")
dev.off()

plot(data02$date_time,data02$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(data02$date_time,data02$Sub_metering_2,type="l",col="red")
points(data02$date_time,data02$Sub_metering_3,type="l",col="blue")
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.75)
dev.copy(png,file="plot3.png")
dev.off()

par(mfrow=c(2,2),mar=c(4,4,2,1),oma=c(0,0,2,0))
plot(data02$date_time,data02$Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)",xlab="")
plot(data02$date_time,data02$Voltage,type = "l",ylab = "Voltage",xlab="datetime")
plot(data02$date_time,data02$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(data02$date_time,data02$Sub_metering_2,type="l",col="red")
points(data02$date_time,data02$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),lty=1,lwd=2,bty="n",cex=0.5,xjust=1,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data02$date_time,data02$Global_reactive_power,type = "l",ylab = "Global_reactive_power",xlab="datetime")
dev.copy(png,file="plot4.png")
dev.off()